/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Urod;

import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author 44785
 */
public class Quotation extends javax.swing.JFrame {

    // ─── Database Configuration ─────────────────────────────────────────
    private static final String DB_PATH = "src/Data/Quotes.accdb";
    private static final String DB_URL = "jdbc:ucanaccess://" + DB_PATH;

    // ─── Data Lists for Combo Boxes ─────────────────────────────────────
    private ArrayList<Quote> readQuotesList = new ArrayList<>();
    private ArrayList<Quote> deleteQuotesList = new ArrayList<>();
    private ArrayList<Quote> updateQuotesList = new ArrayList<>();

    // ─── Quote Data Class ──────────────────────────────────────────────
    static class Quote {
        int id;
        String text;
        String author;

        Quote(int id, String text, String author) {
            this.id = id;
            this.text = text;
            this.author = author;
        }

        @Override
        public String toString() {
            return id + " \u2013 " + author;
        }
    }

    /**
     * Creates new form Quotation
     */
    public Quotation() {
        initComponents();
        initEventHandlers();
        loadReadQuotes();
        loadDeleteQuotes();
        loadUpdateQuotes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblQuotation = new javax.swing.JLabel();
        tabName = new javax.swing.JTabbedPane();
        pnlRead = new javax.swing.JPanel();
        lblReadQuotes = new javax.swing.JLabel();
        cboReadQuotes = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaReadQuotations = new javax.swing.JTextArea();
        lblReadAuthor = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();

        // ─── Insert Panel Components ────────────────────────────────────
        pnlInsert = new javax.swing.JPanel();
        lblInsertQuote = new javax.swing.JLabel();
        jScrollPaneInsertQuote = new javax.swing.JScrollPane();
        txtInsertQuote = new javax.swing.JTextArea();
        lblInsertAuthor = new javax.swing.JLabel();
        txtInsertAuthor = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();

        // ─── Delete Panel Components ────────────────────────────────────
        pnlDelete = new javax.swing.JPanel();
        lblDeleteSelect = new javax.swing.JLabel();
        cboDeleteQuotes = new javax.swing.JComboBox<>();
        btnDeleteRefresh = new javax.swing.JButton();
        jScrollPaneDeletePreview = new javax.swing.JScrollPane();
        txtareaDeletePreview = new javax.swing.JTextArea();
        lblDeleteAuthorLabel = new javax.swing.JLabel();
        lblDeleteAuthorInfo = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();

        // ─── Update Panel Components ────────────────────────────────────
        pnlUpdate = new javax.swing.JPanel();
        lblUpdateSelect = new javax.swing.JLabel();
        cboUpdateQuotes = new javax.swing.JComboBox<>();
        btnUpdateRefresh = new javax.swing.JButton();
        lblUpdateQuoteLabel = new javax.swing.JLabel();
        jScrollPaneUpdateQuote = new javax.swing.JScrollPane();
        txtareaUpdateQuote = new javax.swing.JTextArea();
        lblUpdateAuthorLabel = new javax.swing.JLabel();
        txtUpdateAuthor = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();

        // ─── Search Panel Components ────────────────────────────────────
        pnlSearch = new javax.swing.JPanel();
        lblSearchTerm = new javax.swing.JLabel();
        txtSearchTerm = new javax.swing.JTextField();
        lblSearchBy = new javax.swing.JLabel();
        cboSearchBy = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        jScrollPaneSearchResults = new javax.swing.JScrollPane();
        txtareaSearchResults = new javax.swing.JTextArea();

        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quotations");

        // ════════════════════════════════════════════════════════════════
        //  HEADER LABEL
        // ════════════════════════════════════════════════════════════════
        lblQuotation.setBackground(new java.awt.Color(204, 255, 255));
        lblQuotation.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblQuotation.setText("Quotations");

        // ════════════════════════════════════════════════════════════════
        //  READ PANEL
        // ════════════════════════════════════════════════════════════════
        lblReadQuotes.setText("Quotes");

        txtareaReadQuotations.setColumns(20);
        txtareaReadQuotations.setRows(5);
        txtareaReadQuotations.setEditable(false);
        txtareaReadQuotations.setLineWrap(true);
        txtareaReadQuotations.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtareaReadQuotations);

        lblReadAuthor.setText("Author");

        btnRefresh.setText("Refresh");

        javax.swing.GroupLayout pnlReadLayout = new javax.swing.GroupLayout(pnlRead);
        pnlRead.setLayout(pnlReadLayout);
        pnlReadLayout.setHorizontalGroup(
            pnlReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReadLayout.createSequentialGroup()
                        .addComponent(lblReadQuotes)
                        .addGap(61, 61, 61)
                        .addComponent(cboReadQuotes, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lblReadAuthor)
                        .addGap(0, 130, Short.MAX_VALUE))
                    .addGroup(pnlReadLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefresh)))
                .addContainerGap())
        );
        pnlReadLayout.setVerticalGroup(
            pnlReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReadLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRefresh)
                    .addGroup(pnlReadLayout.createSequentialGroup()
                        .addGroup(pnlReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblReadQuotes)
                            .addComponent(cboReadQuotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblReadAuthor))
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        tabName.addTab("Read", pnlRead);

        // ════════════════════════════════════════════════════════════════
        //  INSERT PANEL
        // ════════════════════════════════════════════════════════════════
        lblInsertQuote.setText("Quote:");

        txtInsertQuote.setColumns(20);
        txtInsertQuote.setRows(5);
        txtInsertQuote.setLineWrap(true);
        txtInsertQuote.setWrapStyleWord(true);
        jScrollPaneInsertQuote.setViewportView(txtInsertQuote);

        lblInsertAuthor.setText("Author:");

        btnInsert.setText("Insert");
        btnInsert.setFont(new java.awt.Font("Tahoma", 1, 12));

        javax.swing.GroupLayout pnlInsertLayout = new javax.swing.GroupLayout(pnlInsert);
        pnlInsert.setLayout(pnlInsertLayout);
        pnlInsertLayout.setHorizontalGroup(
            pnlInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInsertLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInsertQuote)
                    .addComponent(jScrollPaneInsertQuote, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addGroup(pnlInsertLayout.createSequentialGroup()
                        .addComponent(lblInsertAuthor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInsertAuthor))
                    .addGroup(pnlInsertLayout.createSequentialGroup()
                        .addComponent(btnInsert)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlInsertLayout.setVerticalGroup(
            pnlInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInsertLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblInsertQuote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneInsertQuote, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInsertAuthor)
                    .addComponent(txtInsertAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnInsert)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        tabName.addTab("Insert", pnlInsert);

        // ════════════════════════════════════════════════════════════════
        //  DELETE PANEL
        // ════════════════════════════════════════════════════════════════
        lblDeleteSelect.setText("Select Quote:");

        btnDeleteRefresh.setText("Refresh");

        txtareaDeletePreview.setColumns(20);
        txtareaDeletePreview.setRows(5);
        txtareaDeletePreview.setEditable(false);
        txtareaDeletePreview.setLineWrap(true);
        txtareaDeletePreview.setWrapStyleWord(true);
        jScrollPaneDeletePreview.setViewportView(txtareaDeletePreview);

        lblDeleteAuthorLabel.setText("Author:");
        lblDeleteAuthorInfo.setText(" ");
        lblDeleteAuthorInfo.setFont(new java.awt.Font("Tahoma", 1, 12));

        btnDelete.setText("Delete");
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnDelete.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout pnlDeleteLayout = new javax.swing.GroupLayout(pnlDelete);
        pnlDelete.setLayout(pnlDeleteLayout);
        pnlDeleteLayout.setHorizontalGroup(
            pnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeleteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDeleteLayout.createSequentialGroup()
                        .addComponent(lblDeleteSelect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboDeleteQuotes, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteRefresh)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPaneDeletePreview, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addGroup(pnlDeleteLayout.createSequentialGroup()
                        .addComponent(lblDeleteAuthorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDeleteAuthorInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlDeleteLayout.createSequentialGroup()
                        .addComponent(btnDelete)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlDeleteLayout.setVerticalGroup(
            pnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeleteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeleteSelect)
                    .addComponent(cboDeleteQuotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteRefresh))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneDeletePreview, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeleteAuthorLabel)
                    .addComponent(lblDeleteAuthorInfo))
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        tabName.addTab("Delete", pnlDelete);

        // ════════════════════════════════════════════════════════════════
        //  UPDATE PANEL
        // ════════════════════════════════════════════════════════════════
        lblUpdateSelect.setText("Select Quote:");

        btnUpdateRefresh.setText("Refresh");

        lblUpdateQuoteLabel.setText("Quote:");

        txtareaUpdateQuote.setColumns(20);
        txtareaUpdateQuote.setRows(5);
        txtareaUpdateQuote.setLineWrap(true);
        txtareaUpdateQuote.setWrapStyleWord(true);
        jScrollPaneUpdateQuote.setViewportView(txtareaUpdateQuote);

        lblUpdateAuthorLabel.setText("Author:");

        btnUpdate.setText("Update");
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnUpdate.setForeground(new java.awt.Color(0, 102, 0));

        javax.swing.GroupLayout pnlUpdateLayout = new javax.swing.GroupLayout(pnlUpdate);
        pnlUpdate.setLayout(pnlUpdateLayout);
        pnlUpdateLayout.setHorizontalGroup(
            pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUpdateLayout.createSequentialGroup()
                        .addComponent(lblUpdateSelect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboUpdateQuotes, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateRefresh)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblUpdateQuoteLabel)
                    .addComponent(jScrollPaneUpdateQuote, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addGroup(pnlUpdateLayout.createSequentialGroup()
                        .addComponent(lblUpdateAuthorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUpdateAuthor))
                    .addGroup(pnlUpdateLayout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlUpdateLayout.setVerticalGroup(
            pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdateLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpdateSelect)
                    .addComponent(cboUpdateQuotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateRefresh))
                .addGap(18, 18, 18)
                .addComponent(lblUpdateQuoteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneUpdateQuote, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpdateAuthorLabel)
                    .addComponent(txtUpdateAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tabName.addTab("Update", pnlUpdate);

        // ════════════════════════════════════════════════════════════════
        //  SEARCH PANEL
        // ════════════════════════════════════════════════════════════════
        lblSearchTerm.setText("Search:");

        lblSearchBy.setText("By:");

        cboSearchBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quote", "Author" }));

        btnSearch.setText("Search");
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 12));

        txtareaSearchResults.setColumns(20);
        txtareaSearchResults.setRows(10);
        txtareaSearchResults.setEditable(false);
        txtareaSearchResults.setLineWrap(true);
        txtareaSearchResults.setWrapStyleWord(true);
        jScrollPaneSearchResults.setViewportView(txtareaSearchResults);

        javax.swing.GroupLayout pnlSearchLayout = new javax.swing.GroupLayout(pnlSearch);
        pnlSearch.setLayout(pnlSearchLayout);
        pnlSearchLayout.setHorizontalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSearchLayout.createSequentialGroup()
                        .addComponent(lblSearchTerm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSearchBy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboSearchBy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPaneSearchResults, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlSearchLayout.setVerticalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchTerm)
                    .addComponent(txtSearchTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearchBy)
                    .addComponent(cboSearchBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneSearchResults, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabName.addTab("Search", pnlSearch);

        // ════════════════════════════════════════════════════════════════
        //  CLOSE BUTTON
        // ════════════════════════════════════════════════════════════════
        btnClose.setText("Close");

        // ════════════════════════════════════════════════════════════════
        //  MAIN FRAME LAYOUT
        // ════════════════════════════════════════════════════════════════
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(lblQuotation, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tabName, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnClose)
                        .addGap(53, 53, 53))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuotation, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tabName, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(38, 38, 38))
        );

        tabName.getAccessibleContext().setAccessibleName("tabName");
        btnClose.getAccessibleContext().setAccessibleName("btnClose");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    // ════════════════════════════════════════════════════════════════════
    //  EVENT HANDLERS
    // ════════════════════════════════════════════════════════════════════

    private void initEventHandlers() {

        // ── Read Tab ────────────────────────────────────────────────────
        cboReadQuotes.addActionListener(evt -> {
            int index = cboReadQuotes.getSelectedIndex() - 1;
            if (index >= 0 && index < readQuotesList.size()) {
                Quote q = readQuotesList.get(index);
                txtareaReadQuotations.setText(q.text);
                lblReadAuthor.setText("Author: " + q.author);
            } else {
                txtareaReadQuotations.setText("");
                lblReadAuthor.setText("Author");
            }
        });

        btnRefresh.addActionListener(evt -> loadReadQuotes());

        // ── Insert Tab ──────────────────────────────────────────────────
        btnInsert.addActionListener(evt -> insertQuote());

        // ── Delete Tab ──────────────────────────────────────────────────
        cboDeleteQuotes.addActionListener(evt -> {
            int index = cboDeleteQuotes.getSelectedIndex() - 1;
            if (index >= 0 && index < deleteQuotesList.size()) {
                Quote q = deleteQuotesList.get(index);
                txtareaDeletePreview.setText(q.text);
                lblDeleteAuthorInfo.setText(q.author);
            } else {
                txtareaDeletePreview.setText("");
                lblDeleteAuthorInfo.setText(" ");
            }
        });

        btnDeleteRefresh.addActionListener(evt -> loadDeleteQuotes());
        btnDelete.addActionListener(evt -> deleteQuote());

        // ── Update Tab ──────────────────────────────────────────────────
        cboUpdateQuotes.addActionListener(evt -> {
            int index = cboUpdateQuotes.getSelectedIndex() - 1;
            if (index >= 0 && index < updateQuotesList.size()) {
                Quote q = updateQuotesList.get(index);
                txtareaUpdateQuote.setText(q.text);
                txtUpdateAuthor.setText(q.author);
            } else {
                txtareaUpdateQuote.setText("");
                txtUpdateAuthor.setText("");
            }
        });

        btnUpdateRefresh.addActionListener(evt -> loadUpdateQuotes());
        btnUpdate.addActionListener(evt -> updateQuote());

        // ── Search Tab ──────────────────────────────────────────────────
        btnSearch.addActionListener(evt -> searchQuotes());

        // ── Close ───────────────────────────────────────────────────────
        btnClose.addActionListener(evt -> System.exit(0));
    }

    // ════════════════════════════════════════════════════════════════════
    //  DATABASE HELPER METHODS
    // ════════════════════════════════════════════════════════════════════

    private Connection getConnection() throws SQLException {
        return DriverManager.getConnection(DB_URL);
    }

    private ArrayList<Quote> getAllQuotes() {
        ArrayList<Quote> quotes = new ArrayList<>();
        String sql = "SELECT * FROM Quotations ORDER BY ID";
        try (Connection conn = getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {
            while (rs.next()) {
                quotes.add(new Quote(
                    rs.getInt("ID"),
                    rs.getString("Quote"),
                    rs.getString("Author")
                ));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Database error:\n" + e.getMessage(),
                "Database Error", JOptionPane.ERROR_MESSAGE);
        }
        return quotes;
    }

    // ════════════════════════════════════════════════════════════════════
    //  LOAD COMBO BOXES
    // ════════════════════════════════════════════════════════════════════

    private void loadReadQuotes() {
        readQuotesList = getAllQuotes();
        cboReadQuotes.removeAllItems();
        cboReadQuotes.addItem("-- Select a Quote --");
        for (Quote q : readQuotesList) {
            cboReadQuotes.addItem(q.toString());
        }
        txtareaReadQuotations.setText("");
        lblReadAuthor.setText("Author");
    }

    private void loadDeleteQuotes() {
        deleteQuotesList = getAllQuotes();
        cboDeleteQuotes.removeAllItems();
        cboDeleteQuotes.addItem("-- Select a Quote --");
        for (Quote q : deleteQuotesList) {
            cboDeleteQuotes.addItem(q.toString());
        }
        txtareaDeletePreview.setText("");
        lblDeleteAuthorInfo.setText(" ");
    }

    private void loadUpdateQuotes() {
        updateQuotesList = getAllQuotes();
        cboUpdateQuotes.removeAllItems();
        cboUpdateQuotes.addItem("-- Select a Quote --");
        for (Quote q : updateQuotesList) {
            cboUpdateQuotes.addItem(q.toString());
        }
        txtareaUpdateQuote.setText("");
        txtUpdateAuthor.setText("");
    }

    private void refreshAll() {
        loadReadQuotes();
        loadDeleteQuotes();
        loadUpdateQuotes();
    }

    // ════════════════════════════════════════════════════════════════════
    //  CRUD OPERATIONS
    // ════════════════════════════════════════════════════════════════════

    // ── INSERT ──────────────────────────────────────────────────────────
    private void insertQuote() {
        String quote = txtInsertQuote.getText().trim();
        String author = txtInsertAuthor.getText().trim();

        if (quote.isEmpty() || author.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Please fill in both Quote and Author.",
                "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sql = "INSERT INTO Quotations (Quote, Author) VALUES (?, ?)";
        try (Connection conn = getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, quote);
            pstmt.setString(2, author);
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this,
                "Quote inserted successfully!",
                "Success", JOptionPane.INFORMATION_MESSAGE);
            txtInsertQuote.setText("");
            txtInsertAuthor.setText("");
            refreshAll();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Error inserting quote:\n" + e.getMessage(),
                "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // ── DELETE ──────────────────────────────────────────────────────────
    private void deleteQuote() {
        int index = cboDeleteQuotes.getSelectedIndex() - 1;
        if (index < 0) {
            JOptionPane.showMessageDialog(this,
                "Please select a quote to delete.",
                "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Quote q = deleteQuotesList.get(index);
        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete this quote?\n\n"
            + "\"" + (q.text.length() > 60 ? q.text.substring(0, 60) + "..." : q.text) + "\"\n"
            + "— " + q.author,
            "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (confirm != JOptionPane.YES_OPTION) return;

        String sql = "DELETE FROM Quotations WHERE ID = ?";
        try (Connection conn = getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setInt(1, q.id);
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this,
                "Quote deleted successfully!",
                "Success", JOptionPane.INFORMATION_MESSAGE);
            refreshAll();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Error deleting quote:\n" + e.getMessage(),
                "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // ── UPDATE ──────────────────────────────────────────────────────────
    private void updateQuote() {
        int index = cboUpdateQuotes.getSelectedIndex() - 1;
        if (index < 0) {
            JOptionPane.showMessageDialog(this,
                "Please select a quote to update.",
                "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String quote = txtareaUpdateQuote.getText().trim();
        String author = txtUpdateAuthor.getText().trim();

        if (quote.isEmpty() || author.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Please fill in both Quote and Author.",
                "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Quote q = updateQuotesList.get(index);
        String sql = "UPDATE Quotations SET Quote = ?, Author = ? WHERE ID = ?";
        try (Connection conn = getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, quote);
            pstmt.setString(2, author);
            pstmt.setInt(3, q.id);
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this,
                "Quote updated successfully!",
                "Success", JOptionPane.INFORMATION_MESSAGE);
            refreshAll();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Error updating quote:\n" + e.getMessage(),
                "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // ── SEARCH ──────────────────────────────────────────────────────────
    private void searchQuotes() {
        String term = txtSearchTerm.getText().trim();
        String searchBy = (String) cboSearchBy.getSelectedItem();

        if (term.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Please enter a search term.",
                "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String column = "Author".equals(searchBy) ? "Author" : "Quote";
        String sql = "SELECT * FROM Quotations WHERE " + column + " LIKE ? ORDER BY ID";
        StringBuilder results = new StringBuilder();

        try (Connection conn = getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, "%" + term + "%");
            try (ResultSet rs = pstmt.executeQuery()) {
                int count = 0;
                while (rs.next()) {
                    count++;
                    results.append("ID: ").append(rs.getInt("ID")).append("\n");
                    results.append("Quote: ").append(rs.getString("Quote")).append("\n");
                    results.append("Author: ").append(rs.getString("Author")).append("\n");
                    results.append("\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500"
                                 + "\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500"
                                 + "\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n");
                }
                if (count == 0) {
                    results.append("No quotes found matching \"").append(term)
                          .append("\" in ").append(column).append(".");
                } else {
                    results.insert(0, "Found " + count + " result(s) for \""
                                       + term + "\" in " + column + ":\n\n");
                }
            }
        } catch (SQLException e) {
            results.append("Error: ").append(e.getMessage());
        }

        txtareaSearchResults.setText(results.toString());
    }

    // ════════════════════════════════════════════════════════════════════
    //  MAIN METHOD
    // ════════════════════════════════════════════════════════════════════

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quotation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quotation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quotation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quotation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quotation().setVisible(true);
            }
        });
    }

    // ════════════════════════════════════════════════════════════════════
    //  VARIABLES DECLARATION - do not modify
    // ════════════════════════════════════════════════════════════════════
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteRefresh;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateRefresh;
    private javax.swing.JComboBox<String> cboDeleteQuotes;
    private javax.swing.JComboBox<String> cboReadQuotes;
    private javax.swing.JComboBox<String> cboSearchBy;
    private javax.swing.JComboBox<String> cboUpdateQuotes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneDeletePreview;
    private javax.swing.JScrollPane jScrollPaneInsertQuote;
    private javax.swing.JScrollPane jScrollPaneSearchResults;
    private javax.swing.JScrollPane jScrollPaneUpdateQuote;
    private javax.swing.JLabel lblDeleteAuthorInfo;
    private javax.swing.JLabel lblDeleteAuthorLabel;
    private javax.swing.JLabel lblDeleteSelect;
    private javax.swing.JLabel lblInsertAuthor;
    private javax.swing.JLabel lblInsertQuote;
    private javax.swing.JLabel lblQuotation;
    private javax.swing.JLabel lblReadAuthor;
    private javax.swing.JLabel lblReadQuotes;
    private javax.swing.JLabel lblSearchBy;
    private javax.swing.JLabel lblSearchTerm;
    private javax.swing.JLabel lblUpdateAuthorLabel;
    private javax.swing.JLabel lblUpdateQuoteLabel;
    private javax.swing.JLabel lblUpdateSelect;
    private javax.swing.JPanel pnlDelete;
    private javax.swing.JPanel pnlInsert;
    private javax.swing.JPanel pnlRead;
    private javax.swing.JPanel pnlSearch;
    private javax.swing.JPanel pnlUpdate;
    private javax.swing.JTabbedPane tabName;
    private javax.swing.JTextArea txtInsertQuote;
    private javax.swing.JTextField txtInsertAuthor;
    private javax.swing.JTextField txtSearchTerm;
    private javax.swing.JTextField txtUpdateAuthor;
    private javax.swing.JTextArea txtareaDeletePreview;
    private javax.swing.JTextArea txtareaReadQuotations;
    private javax.swing.JTextArea txtareaSearchResults;
    private javax.swing.JTextArea txtareaUpdateQuote;
    // End of variables declaration                   
}